pub(super) const EXECUTION_TEMPLATES: &[(&str, &str)] = &[
    ("list", "Count: {{ count }}"),
    ("list-2", "{{ name }}: {{ value }}"),
    ("config/get", "{{ key }}"),
    ("list-3", "Items: {{ items }}"),
    ("list-4", "{{ count }}"),
    ("list-5", "{{ msg }}"),
    ("config/get-2", "{{ value }}"),
    ("other", "{{ msg }}"),
    ("list-6", "Count: {{ count }}, Modified: {{ modified }}"),
    ("list-7", "{{ items }}"),
    ("list-8", "{{ value }}"),
    ("add", "Added: {{ added }}"),
    ("list-9", "{{ cmd }}"),
    ("add-2", "{{ cmd }}"),
    ("show", "unused"),
    ("show-2", "Hello {{ name }}"),
    ("show-3", "Count: {{ count }}"),
    ("list-10", "[late]{{ name }}[/late]"),
    ("list-11", "[test_style]{{ name }}[/test_style]"),
    ("list-12", "[header]{{ title }}[/header]"),
    ("test", "[mystyle]{{ x }}[/mystyle]"),
    ("list-13", "{{ db_url }}"),
    ("list-14", "debug={{ debug }}"),
    ("info", "db={{ db }}, version={{ version }}"),
    ("list-15", "db={{ db }}, user={{ user }}"),
    ("fetch", "{{ url }}"),
    ("test-3", "[perm]{{ val }}[/perm]"),
    ("apply", "{{ done }} done"),
    ("apply.event", "starting {{ event.resource }}"),
];
